## Perspectives in Alberta: Jobs and Energy
#### [Marc Vermette](https://www.linkedin.com/in/marc-vermette/)

Alberta’s premier, Danielle Smith, [criticized](https://twitter.com/ABDanielleSmith/status/1611119725135757317) the [federal government’s intentions](https://www.rncanengagenrcan.ca/en/collections/just-transition) regarding the continued transition towards renewable energy. 

She called the plans [“ill-conceived, “short-sighted,” and “detrimental to Canada’s economic recovery.”](https://twitter.com/ABDanielleSmith/status/1610418366145253377)

However, Jonathan Wilkinson, the Canadian Minister of Natural Resources, claims recent efforts “[encourage] sustainable job creation and economic growth in every region of the country.” 

Wilkinson is not concerned that energy workers will be out of jobs and instead asserts that he is more concerned that there will not be enough people to fill the jobs created by new opportunities in Canadian renewable energy.

Andrew Leach, an energy and economics professor at the University of Alberta (and owner of this website), highlighted the flaws in Alberta’s recent decision to decline to participate in the “regional energy resource tables” led by the federal government, emphasizing the importance of government involvement throughout an energy transition, especially in Alberta.

[Read more here](https://www.cbc.ca/news/canada/calgary/federal-legislation-net-zero-1.6702333)