## A Second Life for EV Batteries
#### [Yousaff Habib](https://www.linkedin.com/in/yousaff-habib-6684891a5/)

A California energy start-up is leading the way in re-purposing old electric vehicle (EV) batteries into solar power storage units. The company, B2U Storage Solutions, has used "second-life" EV batteries from Honda and Nissan to reach 25 MWh of solar storage capacity at its Sierra facility in Lancaster.

The company's proprietary plug-and-play technology utilizes the existing management systems of battery packs, virtually eliminating re-purposing costs and making the technology cost-effective. During the day, the facility's batteries are charged by nearby solar panels and the power is sold back to the grid at night, when rates for solar power are higher. The facility generated over a million dollars in revenue last year.

According to Freeman Hall, co-founder and president of B2U, repurposed EV batteries are a good fit for solar storage as the job is less stressful than powering a car. The use of re-purposed EV batteries should result in a longer second lifespan, as the current used is much less than what the batteries are rated for, and they are not pushed to their voltage limits.

As early EV owners upgrade to newer models, the available supply of used batteries is expected to skyrocket and many could be turned into alternative energy storage solutions. This move could have far-reaching implications, with other industries, such as car manufacturers and airlines, exploring similar technology in their efforts to decarbonize their production lines and implement small-scale onsite energy storage. B2U's Sierra facility serves as a demonstration of the potential of second-life EV batteries as solar storage units on a worthwhile scale.

You can find out more information on B2U Storage Solutions [website](https://www.b2uco.com/). This method of recycling is exactly what the renewable market as a whole should be looking at, in order to ensure that it is as sustainable as possible. The market as a whole would greatly benefit from more projects in the same vein as this.