## Blueberry River Deal
#### Kayla Layden

The Province of British Columbia announced Wednesday that it had reached a long-awaited agreement with the Blueberry River First Nations. The plan comes almost 19 months after the B.C. Supreme Court ruled that the government had violated Blueberry River's Treaty 8 rights by allowing industrial development without the community's approval. The ruling and subsequent negotiations led to a freeze on new oil and gas licenses in B.C.'s lucrative Montney shale play since June 2021.

The released agreement includes a new planning regime to manage future oil and gas development in the roughly 38,000-kilometre area. The main change for industry will come in the form of limits on new land disturbance - an annual cap of 750 hectares. In the five years preceding the court decision, the average yearly new land disturbance was 1,500 hectares meaning the new cap will require a focused effort from industry and likely increased use of technologies like horizontal drilling that allow expansion without disturbing additional land. There are currently no restrictions announced for already developed land. More than 650,000 hectares of particular value and significance to Blueberry River will also be protected from any resource development. 

The announcement was met with general support from industry, with many celebrating the possibility of development again, even with increased scrutiny and land disturbance limits. While some questions remain, including how the allotted 750 hectares will be allocated, the potential for new permit approvals and decreased uncertainty seem to have prompted cautious optimism.
 
[Original Article](https://financialpost.com/commodities/energy/oil-gas/blueberry-river-deal-no-longer-business-as-usual-montney-gas-producers)