## Back to the Boom?

#### <font size="+2"> Erica Beattie

Bloomberg commentary in the FP from Randy Thanthong-Knight this week is bullish, arguing that we are back in a [boom in Alberta](https://financialpost.com/news/economy/alberta-oil-boom-times-back). Inflation has been making headlines across the country because of the cost of living impacts, but the other side to that coin is bull markets for commodities such as oil, natural gas, wheat, and barley, all of which are key Alberta exports. As just one example of the economic turnaround, Calgary is now back among the highest [employment rates](https://data.calgary.ca/Business-and-Economic-Activity/Employment-Rates/a3cq-4yfn) of any large Canadian city, and Alberta is predicted by most analysts to top the country in terms of economic growth and job creation. As ever, economists must have two hands. The op-ed worries that commodity exports remain the primary driver in Canada's economy and sees environmental policies are cutting against that growth. 
