## More on BP's Oil Sands Exit 

#### Debosree Mukherjee

[BP will be fully exiting the Alberta oil-sands market](https://www.cbc.ca/news/canada/newfoundland-labrador/bay-du-nord-bp-1.6486602) by selling its 50% stake in the Sunrise project to Cenovus. BP is acquiring Cenovus's 35% stake in Newfoundland and Labrador's undeveloped offshore oil project, Bay du Nord, in the deal. Cenovus will be buying BP's stake in Sunrise for $600 million in cash and a contingent payment of $600 million linked to the price of oil over the next two years. The transaction is expected to close before the end of 2022. This decision aligns with BP's plans to divest from oil-sands due to image concerns associated with higher upstream emissions. Bay du Nord is being promoted as Canada's lowest emitting oil project. However, [environmental groups are opposing the Bay du Nord project](https://www.cbc.ca/news/canada/newfoundland-labrador/bay-du-nord-lawsuit-launched-1.6449379) and BP's involvement in it due to concerns of potential spills.   

