## Renewable Energy in Canada’s New Budget

#### [Marc Vermette](https://www.linkedin.com/in/marc-vermette/)

Nearly 15% of new spending in [Canada’s 2023 budget](https://www.budget.canada.ca/2023/home-accueil-en.html) is expected to go towards renewable energy in Canada.

This new spending includes a 15% tax credit for investments made regarding renewable energy infrastructure (wind, solar plants, nuclear reactors, batteries, etc.)

While this tax credit begins a year from now, it will be available for 10 years, costing ~$25.7 billion by 2035, when it comes to an end.

On top of this tax credit, an additional $3 billion program will be added within the next 12 years that provides grants to companies and governments looking to modernize existing power grids.

While this might seem like a drop in the (solar powered?) bucket compared to the expected [$1.7 trillion](https://renewablesassociation.ca/wp-content/uploads/2021/11/CanREAs2050Vision_Nov2021_web.pdf) Canada estimates it needs to reach net zero by 2050, renewable energy is becoming cheaper and more accessible by the day. 

[Original Article](https://www.nationalobserver.com/2023/03/30/news/five-takeaways-canadas-electricity-overhaul)