## Cenovus 2023 Forecast
#### [Erica Beattie](https://www.linkedin.com/in/erica-beattie-594b471a1/?originalSubdomain=ca)

Earlier this week, Canada's Cenovus Energy Inc. announced its [2023 budget](https://www.cenovus.com/News-and-Stories/News-releases/2022/2568065), which forecasts a higher capital expenditure for the upcoming year. The energy producer expects an increase of more than 3% in total upstream production of barrels of oil - between 800,000 and 840,000 barrels of oil equivalent/day. In terms of spending, Cenovus anticipates 2023 capital spend to be between $4 billion to $4.5 billion - a significant increase from this year's budget of between $3.3 and $3.7 billion.

The Calgary Herald published an article discussing Cenovus' budget and outlining the global energy industry factors that are driving this increase in spending. A significant one that many are aware of, is the invasion of major oil exporter Russia over Ukraine. This further limited already tight supplies, resulting in an increase in crude oil prices of up to 79% this year. To amplify these limitations, as of Monday December 5, the [Eupean Union banned Russian crude imports](https://www.consilium.europa.eu/en/policies/sanctions/restrictive-measures-against-russia-over-ukraine/sanctions-against-russia-explained/#:~:text=The%20EU%20has%20prohibited%20the,or%20financing%20or%20financial%20assistance.).

Echoing Cenovus' message, [Suncor Energy](https://www.reuters.com/business/energy/suncor-energy-forecasts-higher-spend-2023-2022-11-29/) and [Canadian Natural Resources](https://financialpost.com/commodities/energy/oil-gas/canadian-natural-resources-forecasts-higher-production) have also stated a prediction of higher capital expenditure in the new year. Energy producers are feeling the pressure of today's industry, especially with rising costs and shortages of both labour and materials, and we will see these pressures reflected in prices.