## COP27 Update
#### [Erica Beattie](https://www.linkedin.com/in/erica-beattie-594b471a1)

World leaders are meeting in Sharm el Sheikh, Egypt, for [two weeks of climate negotiations](https://news.un.org/en/story/2022/10/1129947), set to end on November 18th. Oil and gas industry representatives joined the Canadian delegation, and their [presence has led to criticism](https://calgaryherald.com/commodities/energy/ruffing-some-feathers-at-cop27-canada-includes-oil-and-gas-companies-in-its-delegation/wcm/79b6e7de-7d3e-4c2a-a018-3bbfcfafe9bc).Environmental groups and climate activists are pointing out the irony of the situation: an industry responsible for large amounts of emissions taking part in an event dedicated to climate action. Industry argues that their participation is crucial, as collaboration with industry will help us meet Canada’s climate goals. Ideally, Canada’s oil gas industry will find ways to maintain its operations while reducing emissions, and end up as part of the climate crisis solution. 

Later this week, a presentation by the Pathways Alliance, representing Canada's six largest oilsands companies, will lay out the industry's plan to reduce emissions. Some components of this plan include large investments in carbon-capture and storage projects, as well as other clean technologies. 

Another dire issue looming over this year's UN climate conference is the global energy crisis resulting from tight energy supplies and Russia's invasion of Ukraine.