## Cryptomining and its many costs
#### [Yousaff Habib](https://www.linkedin.com/in/yousaff-habib-6684891a5/)

Following a ban on mining cryptocurrency in China, the United States has become a hub for cryptomining. With [38%](https://www.warren.senate.gov/imo/media/doc/2022.07.15%20Letter%20to%20EPA%20and%20DOE%20Re%20Cryptomining%20Environmental%20Impacts.pdf) of all global computing power dedicated to mining Bitcoin coming from the US, and other altcoins being similarly over represented, cryptocurrency and mining has taken a firm foothold in the US. For those uninitiated with what cryptomining is, simply put, it is solving complex problems using computers in exchange for cryptocurrency. The many computers involved require huge amounts of power, which has multiple negative effects. A [recent report](https://www.warren.senate.gov/imo/media/doc/2022.07.15%20Letter%20to%20EPA%20and%20DOE%20Re%20Cryptomining%20Environmental%20Impacts.pdf) from US lawmakers has revealed that in upstate New York, the influx of cryptomining resulted in residential electricity bills "up to $300 higher than usual". Moreover, it revealed that mining results in substantial amounts of carbon emissions -- with the energy used to mine Bitcoin and Ethereum in 2021 resulting in 80 million tons of CO2 emissions. This news is troubling as cryptomining is only [projected to grow](https://www.globenewswire.com/en/news-release/2022/04/12/2420714/0/en/Cryptocurrency-Mining-and-Equipment-Market-Size-2022-2028-Growth-Revenue-Competitive-Scenario-Development-Status-Regional-Segmentation-Key-Players-Opportunities-Challenges.html#:~:text=According%20to%20our%20latest%20research,for%20the%20next%20five%20years.) across the US. In Texas, where massive cryptomining growth is slated for the [next 4 years](https://decrypt.co/105515/texas-bitcoin-miners-power-voluntary-suspension-during-grid-strain), an already strained power grid will need [drastic measures to compensate for this growth](https://www.nbcnews.com/tech/crypto/can-fragile-texas-power-grid-handle-cryptomining-gold-rush-rcna15726). Cryptomining may prove a valuable endavour, but its energy and carbon costs are an important factor we must consider while pursuing it.