## The EU says Natural Gas and Nuclear are Clean Energy!
#### Debosree Mukherjee

On Wednesday, [the EU voted to keep specific nuclear and natural gas usage in its taxonomy of environmentally sustainable economic activities](https://www.europarl.europa.eu/news/en/press-room/20220701IPR34365/taxonomy-meps-do-not-object-to-inclusion-of-gas-and-nuclear-activities). The EU taxonomy is a classification system that establishes a list of environmentally sustainable economic activities for investors, policymakers, and companies. This inclusion will affect how projects are funded in the region. The vote follows a plan presented to classify some natural gas and nuclear power as transitional green investments back in February. This decision has been met with mixed reactions from EU countries, lawmakers, and investors. Natural gas has high emissions relative to renewable sources, but is far greener than coal power. Nuclear power does not generate any direct emissions, however it is criticized due to radioactive waste storage issues and there are some GHGs associated with fuel production. Following the vote, the use of natural gas to generate electricity or to heat buildings will be considered sustainable, but other uses may be excluded. [This is only approved to 2030 or 2035 depending on the situation](https://www.cnbc.com/2022/07/06/europe-natural-gas-nuclear-are-green-energy-in-some-circumstances-.html). New nuclear plants with latest technologies and modifications to extend life of existing plants may be approved to 2040 or 2045. 

Through this inclusion, EU wants to encourage private investment in natural gas and nuclear to transition from dirtier fossil fuels, such as coal, to clean energy. According to the European Climate Law, EU is required to reduce GHG emissions by 55% at the end of the decade to become climate neutral by 2050. 