## Recession in Europe
#### [Debosree Mukherjee](https://www.linkedin.com/in/debosree-mukherjee/)

With Russia cutting off gas flows, a Europe-wide recession seems to be inevitable now. [The continent is gearing up for a harsh winter as energy bills skyrocket](https://www.cbc.ca/news/world/europe-winter-energy-crisis-1.6596446). Even though governments are handing out hundreds of billions of euros to families while bailing out companies, the high price of power is pushing businesses to shutdown as the energy bill is expected to more than triple next year. In Bulgaria, the poorest of the 27 members of EU, more than a quarter of the population can not afford to heat their home.

Building on a model of the European energy market and economy, [the Bloomberg Economics base case](https://www.bloomberg.com/news/articles/2022-09-27/europe-faces-an-energy-crisis-how-bad-could-things-get#xj4y7vzkg) is now a 1% drop in GDP with the downturn starting in the fourth quarter. If the EU members fail to be efficient with the scarce fuel supply and the upcoming winter is extra cold, the drop could be as much as 5%. This would be at the same level as the 2009 recession. Even with a better case scenario, Europe is clearly heading into a deep recession. The European economy is on track to suffer its third biggest contraction since WW2 in 2023.

The European Central Bank is driving the fastest hike of interest rates in its history to minimize the effects of inflation. According to researchers, the effects of the energy crisis on the economy could last up to two-years. While government help is key for businesses to survive in the short term, reforming the energy markets is necessary for a longer-term solution. Environmentalists and EU itself believe that renewables are the way out in the long-term. The demand for solar from households and businesses are soaring. While the supply is also increasing, [solar panels are currently piling up in warehouses in Europe](https://www.bloomberg.com/news/articles/2022-09-27/solar-panels-piling-up-in-warehouses-in-energy-starved-europe) due to not having enough engineers to complete the installations fast enough to keep up with orders.
