## Europe's Largest Solar Plant
#### [Debosree Mukherjee](https://www.linkedin.com/in/debosree-mukherjee/)

Last week, Spanish multinational energy company Iberdrola began operations at Europe’s largest solar plant. The [590 MW Francisco Pizarro solar photovoltaic (PV) project](https://www.power-technology.com/news/iberdrola-francisco-pizarro/) is in Extremadura, Spain. This plant has helped to increase the renewable energy output in the country and decrease its dependence on fossil fuels. One of Iberdrola’s largest facilities, the Francisco Pizarro solar facility was built with an investment of more than 300 million euros. The solar plant consists of more than 1.5 million solar PV modules and has the capacity to generate enough clean energy to [power more than 334,000 homes](https://www.bloomberg.com/news/articles/2022-08-10/sun-drenched-spain-turns-on-europe-s-biggest-solar-power-plant). It will also offset 150,000 tonnes of carbon dioxide emissions per year. Spanish power prices are currently almost 3x higher than the 5-year seasonal average due to Russian gas cuts. Spain is betting that increasing solar generation will help bring these prices down. Spain has a goal to generate 75% of its electricity from renewables by 2030, a big increase from the 47% market share in 2021. 