## Hypocrisy in F1?
#### Erica Beattie

F1 driver Sebastian Vettel arrived at the Montreal Grand Prix in an anti-oilsands t-shirt and proceeded to [criticize Alberta oilsands operations](https://www.cbc.ca/amp/1.6493309) in an interview. His [helmet](https://twitter.com/JMD_helmets/status/1537861959445528577?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1537861959445528577%7Ctwgr%5E%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fglobalnews.ca%2Fnews%2F8929282%2Ff1-driver-sebastian-vettel-alberta-oilsands%2F) also displayed a similar message.

Vettel has used his platform on other occasions to address climate change and other environmental issues. 

Predictably, he received [scathing criticism](https://twitter.com/sonyasavage/status/1537875703613427712?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1537875703613427712%7Ctwgr%5E%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Fd-16108893993922113126.ampproject.net%2F2206071918001%2Fframe.html) from Alberta's Energy Minister Sonya Savage. The hypocrisy of his position made him an easy target: his career relies on fuel and one of his sponsors is Saudi-Arabia's state-owned oil giant Aramco.

The Alberta energy industry has been trying to change people's perception of it for years now, and is even taking steps towards achieving net zero. But it seems that not everyone is convinced that much, if anything, has changed. Unfortunately, neither incidents like these nor the predictable Alberta response do much to improve that perception. 