## IEA Report Predicts Global Demand For Fossil Fuel Will Begin to Wane
#### <font size="+2"> 
#### [Yousaff Habib](https://www.linkedin.com/in/yousaff-habib-6684891a5/)

<!-- <br> -->


Russia's invasion of Ukraine has caused a number of global ripples, primarily ones with negative effects. However, some of these ripples might not all be bad for humanities future according to the latest edition of the IEA's *World Energy Outlook* (WEO). The markets for natural gas, coal and electricity, especially in Europe have been severely disrupted by the current geopolitical situation. Moreover, oil markets, which have been tumultuous over the past few years have been thrown into even more turmoil recently. As such, more and more investments are being made into the renewable energy sector. Perhaps resultantly, the WEO indicates that for the first time ever, global demand for fossil fuel will reach either a peak or plateau by mid 2030's. This is astonishing news as fossil fuel usage has increased alongside GDP since the beginning of the industrial revolution - this paradigm shift may very well mark a turning point for humanity. The report also delineates how the increase in solar PV, wind energy, EV's and new batteries has contributed to the declining use of fossil fuels, and how the development of policy that supports these endeavors could result in an even quicker decline in humanities use of fossil fuels. Russia has historically been the worlds largest exporter of fossil fuels, but the recent actions taken by its regime have resulted in numerous sanctions, even on much coveted oil. As a result, many countries that once relied on these oil exports are currently making the shift to cleaner, greener energy. We've covered some of the bigger projects, especially the ones occurring in Germany on some previous charts, but it seems as though a growing number of countries are beginning to see energy independence as a benefit, and investing in renewable technologies to achieve that. For more information, read the full [WEO here.](https://www.iea.org/reports/world-energy-outlook-2022)
