## Four days for the climate?
#### Erica Beattie

An [article in the Washington Post](https://www.washingtonpost.com/climate-solutions/2022/08/08/4-day-workweek-environment/) argues that reducing the workweek to four days could benefit society, the economy, and even the environment. It mentions [a series of studies](https://research.chalmers.se/en/publication/216709) that have seen a correlation between work time reductions and emissions reduction.

A shortened workweek would directly impact people's commutes and lifestyle choices, as well as businesses' energy usage. Transportation is one of the biggest contributors to greenhouse gas emissions, and so cutting back workers' commuting time has the potential to reduce emissions. This was noticeable during the early months of the pandemic, when the world had to shift to a work-from-home environment. Since then, many have adopted remote or hybrid work models, thereby commuting less. It is important to note that the climate benefits could be reversed should people choose to spend their extra days off travelling, particularly by car or plane. The four-day workweek could also lead to a decrease in energy consumption. For instance, if office buildings are closed for an extra day, that is one less day of using electricity or other energy resources. However, as many people saw during COVID, household energy (and coffee maker!) use increases the more time people spend at home.

The article also argues that fewer work hours can lead to more and more people shifting toward a more sustainable lifestyle. The busier people are, the more likely they are to opt for convenient, time-saving choices, and these tend to be more carbon-intensive. Furthermore, [research](https://www.tandfonline.com/doi/pdf/10.1080/15487733.2005.11907964?needAccess=true) shows that those who work less are more likely to spend their time partaking in traditionally low-carbon activities, like spending time with friends and family.

