## 2022 G7 Summit
#### [Erica Beattie](https://www.linkedin.com/in/erica-beattie-594b471a1/)

This week, the 2022 G7 Summit was held in Germany. Leaders of the largest global economic powers met to discuss matters such as Ukraine, climate change, inflation, food, and energy. The invasion of Ukraine and volatile oil and gas prices were the most pressing issues the leaders faced.

According to the [Executive Summary](https://www.g7germany.de/resource/blob/974430/2057928/1315842ed9de069fa1be82dab18dabb2/2022-06-28-leaders-communique-executive-summ-data.pdf?download=1) of the [G7 Leaders' Communiqué](https://www.g7germany.de/resource/blob/974430/2057828/77d5804dd1ab3047bf0f5f74c1139066/2022-06-28-abschlusserklaerung-eng-web-data.pdf?download=1), the leaders intend to work with partners to establish a "Climate Club" by the end of the year. The club will be committed to "a highly decarbonized road sector by 2030" and "a fully or predominantly decarbonized power sector by 2035," in line with Canadian goals. G7 leaders will also seek to advance climate change mitigation policies towards carbon neutrality, and boost international cooperation through partnerships. A stand-alone statement on the climate club concept can be found [here](https://www.g7germany.de/resource/blob/974430/2057926/2a7cd9f10213a481924492942dd660a1/2022-06-28-g7-climate-club-data.pdf?download=1)

The leaders also recognize that investing in natural gas is "necessary in response to the current crisis", and intend to phase out dependency on Russian energy.

