## Germany's Coal Revival
#### [Erica Beattie](https://www.linkedin.com/in/erica-beattie-594b471a1)

Germany is shifting priorities from climate action to energy security, with its plan to increase coal consumption to minimize the impact of the current energy crisis. [Data compiled from Bloomberg](https://www.bloomberg.com/news/articles/2022-12-22/germany-returns-to-coal-as-energy-security-trumps-climate-goals) shows that the nation is burning more coal for electricity than it has in the last six years. Coal appears to be making a comeback across the globe as countries attempt to stop rising energy costs from causing any more economic turmoil - this crisis is especially prevalant in Europe. Germany is attempting to balance its current energy security dilemma with its long-term goal of net-zero emissions by 2045. Carlos Fernandez Alvarez, the acting head of gas, coal, and power at IEA, made the statement, "... when you face the dilemma to keep the lights on or decrease carbon emissions, the choice is to keep the lights on." 

Germany has plans ideally to phase out coal by 2030, but with the current situation, this goal is looking less realistic. The [original article](https://www.bloomberg.com/news/articles/2022-12-22/germany-returns-to-coal-as-energy-security-trumps-climate-goals) has more details on the cause for this revival of coal, as well as how Germany plans to move forward.

