## Hydrogen community in Strathconca County
#### [Erica Beattie](https://www.linkedin.com/in/erica-beattie-594b471a1/?originalSubdomain=ca)

The [Alberta Hydrogen Centre of Excellence (HCOE)](https://albertainnovates.ca/programs/hydrogen-centre-of-excellence/) is running their first funding competition. They are awarding $20M to 18 successful projects in order to advance innovations in hydrogen, and one of these projects is the proposed Bremner 100% Hydrogen Community in Strathcona County, Alberta. ATCO and Qualico are studying the logistics and feasibility of this project in hopes of creating a unique 100% hydrogen community. The goal is to work towards the elimination of carbon emissions produced by the heating of homes and usage of hot water. Bremner will be Canada's first community of this kind and the largest scale project of its kind globally. 

The projects funded will address the following:

- Development and use of hydrogen-focused technologies
- Creating a clean hydrogen community in Alberta that is both sustainable and self-sifficient
- Advancing Alberta's strength in clean hydrogen technology deployment

More details on the HCOE funding competition and its chosen projects can be found [here](https://energynow.ca/2023/02/20-million-in-hydrogen-funding-awarded-by-the-hydrogen-centre-of-excellence/).
