## Hydrogen Dollars
#### Kayla Layden

On Tuesday, the federal government, through PrairiesCan, announced $9.74 million in funding to support Alberta's hydrogen economy. The new funding is focused on developing and testing technologies, increasing investment, and building Edmonton's status as a hydrogen hub. 

The federal funding will be allocated as follows: 

* $3 million to fund initiatives encouraging increased foreign investment through the not-for-profit Edmonton Global
* $0.74 million to support the development of a supply chain and labour market for hydrogen in Alberta, also through Edmonton Global
* $3 million to the University of Alberta and Alberta Motor Transport Association to make hydrogen fuel more accessible and encourage its use, including through heavy equipment and bus pilot projects in Edmonton and Calgary
* $3 million to upgrade testing facilities at C-FER Technologies, a subsidiary of Alberta Innovates, to help the Edmonton facility test hydrogen fuel infrastructure, equipment, and technologies

The federal government's support comes alongside [$3 million](https://globalnews.ca/news/9416624/federal-government-support-alberta-jobs-hydrogen-industry/) from the province and the Alberta government's Hydrogen Roadmap, released in November of 2021. The Roadmap is designed to "integrate hydrogen with the province's existing energy system and propel Alberta into the global hydrogen economy." You can find official information on the Roadmap [here](https://www.alberta.ca/hydrogen-roadmap.aspx).

[Original Article](https://edmontonjournal.com/news/local-news/federal-minister-at-eia-for-hydrogen-fuel-announcement)