## India-Canada Climate Agreement

#### Debosree Mukherjee

On June 2nd, India and Canada signed a [Memorandum of Understanding](https://www.canada.ca/en/environment-climate-change/news/2022/06/canada-and-india-sign-memorandum-of-understanding-to-establish-stronger-cooperation-on-environmental-protection-and-climate-action.html) to increase cooperation on climate action and environmental protection. Both countries have agreed to collaborate in areas such as

* increasing renewable energy capacity,
* decarbonizing heavy industries,
* reducing plastic pollution,
* supporting the sound management of chemicals,
* ensuring sustainable consumption.

This new agreement gives Canada an opportunity to export its renewable energy technologies to India, the world's third-largest emitter of GHGs. However, it leaves out the production and consumption of coal in India, a key environmental issue. [Coal produced about 40% of the world's emissions in 2020](https://www.ctvnews.ca/climate-and-environment/climate-agreement-between-canada-india-discusses-renewable-energy-but-omits-coal-1.5930406), and India is the second largest producer and consumer of coal. Due to challenges regarding India's growing population, energy demand, and poverty, the country continues to rely heavily on coal. Emissions from coal power in India has nearly tripled from 2000 to 2020. Coal is now responsible for almost half of India's total carbon footprint. In contrast, emissions from coal power in Canada have decreased from 109 million tonnes in 2000 to 35 million tonnes in 2020. Canada's Environment Minister has stated that although coal is not in the agreement, Canada will be looking to export renewable energy expertise to help India phase out its dependency on coal-fired electricity. 