## US inflation at 40-year high!
#### Debosree Mukherjee

In June, [US inflation increased to 9.1%, the highest since November 1981](https://finance.yahoo.com/news/energy-prices-up-41-over-past-12-months-150201870.html)! This was above the 8.8% Dow Jones estimate. Inflation was driven by high oil and gas prices, as the data show that energy contributed to almost half of the all-items increase in the June consumer price index (CPI). 

This should not be surprising since energy prices increased 41.6% over the past year. Gasoline rose 11.2% on a month-over-month basis, and 59.9% over the last 12 months. It was the largest 12 month increase in this index since March 1980. Natural gas rose 8.2% in June which was the largest monthly increase since October 2005. Electricity, bucking the trend a bit, rose 1.7%. 

Canada is also dealing with high inflation at 7.7% with fears of a four-decade high 8% inflation soon. To curb inflation, [Bank of Canada raised its policy rate to 2.5% from 1.5%](https://finance.yahoo.com/news/canada-goes-nuclear-supersized-1-213000679.html) and said more hikes would be needed. This is the highest increase since 1998. 
