## The IRA goes to Europe!
#### [Marc Vermette](https://www.linkedin.com/in/marc-vermette/)

At the EU’s summit last week, member states debated the Green Deal Industrial Plan; their *answer* to the US’s Inflation Reduction Act (IRA).

An analysis by a group of renewable energy companies shows that the [anticipation of the IRA](https://www.theatlantic.com/science/archive/2023/02/inflation-reduction-act-eu-green-deal-industrial-plan/672985/) alone resulted in $40 billion in new investment and the creation of over 7000 jobs in Q4 of 2022.

In Europe, on the other hand, business, industry, and startup confidence has been quickly falling.

Certain battery startups, for example, have already [migrated their operations](https://www.ft.com/content/59a8d135-3477-4d0a-8d12-20c7ef94be07) to the US, where they can more easily and affordably establish their operations.

Specific emergency measures have been recently implemented to reduce red tape for European renewable companies. For example, the EU now expedites permits for wind projects to be granted within six months. However, this only applies to new permits, and any applications submitted before this emergency measure implementation are stuck in limbo.

Many other issues like this may discourage investment in European renewables, and I hope the Green Deal Industrial Plan offers real solutions to this issue.

[Original Article](https://www.bloomberg.com/opinion/articles/2023-02-09/europe-s-green-deal-industrial-plan-has-to-cut-red-tape-on-renewables-investment)