## Irving invests in hydrogen
#### Keshinee Moonian

Irving Oil is expanding hydrogen capacity at its refinery in New Brunswick in a bid to lower carbon emissions and offer clean energy to customers. 

Irving Oil might be on its way to buying a five-megawatt hydrogen electrolyzer which will create two tonnes of hydrogen a day using electricity from the local grid. 

Hydrogen is used to lower the sulphur content of petroleum products like diesel fuel, but producing hydrogen using natural gas creates carbon dioxide emissions. Instead, Irving Oil is using water and electricity to produce “clean hydrogen” through a process called electrolysis. According to Irving, the company is the first to invest in electrolyzer technology.

“New Brunswick Power's electrical system includes 14 generating stations powered by hydro, coal, oil, nuclear and diesel,” according to The Canadian Press.

This investment also allows the company to store and make hydrogen available to the marketplace. Thanks to this technology, Irving will be able to "unlock pent up demand for hydrogen as an energy transition fuel for logistics organizations."


[Irving Oil invests in hydrogen to offer clean energy to customers by lowering emissions](https://energynow.ca/2022/07/irving-oil-invests-in-hydrogen-to-lower-emissions-offer-clean-energy-to-customers/)

