## Keystone Spill Update
#### Kayla Layden

On December 7, 2022, the Keystone pipeline linking Alberta to Oklahoma and the U.S. Gulf Coast, experienced its worst spill to date, leaking diluted bitumen into Mill Creek in Washington County, Kansas. Following the spill, part of the pipeline remained shuttered for almost a month, and operating pressure has been reduced along the line since flows resumed at the end of December. 

This past week, on February 9, TC Energy released updated estimates and preliminary causal findings. The spill's size, originally estimated at 14,000 barrels, was revised down to 12,937 barrels. The company announced a welding flaw and bending stress were to blame, although the cause of this stress is still under investigation as part of a third-party review.

The large spill prompted increased discussion around the safety of pipelines and particularly of Keystone, which has experienced at least 23 spills since 2010. Although most of the incidents have been small, fewer than 50 barrels of oil, the severity seems to be growing; before December's event, the two largest spills in Keystone's history occurred in 2017 and 2019. The U.S. Government Accountability Office raised concerns about Keystone's safety in 2021, especially in light of the pipeline's special permit, which allows the line to operate at a higher stress level than is typically allowed under U.S. federal regulation. The Government Accountability Office's report has prompted a review of the special permitting process.

Clean-up remains a significant challenge, given the impact on both the creek and nearby farmland. As part of the announcement last week, Keystone shared that investigation and remediation are expected to cost $480 million.

[Financial Post Article](https://financialpost.com/commodities/energy/oil-gas/keystone-spill-cleanup-costs-480-million)

[CBC Article](https://www.cbc.ca/news/canada/calgary/tc-energy-keystone-pipeline-leak-cause-1.6742825)    