## Nunatsiavut Renewables
#### [Debosree Mukherjee](https://www.linkedin.com/in/debosree-mukherjee/)

The Inuit government of Nunatsiavut in Newfoundland and Labrador is looking to gain energy independence through solar and wind power. Solar panels have been installed in the community centres of five remote towns. The regional government has the goal to get the towns off diesel power and increase energy-efficiency. The solar panels will help to reduce the region’s heavy reliance on fossil fuels despite being effective only seasonally, with limited generation in winter if snow blocks the panels. However, after [installing 30 solar systems in the Northern communities over the past 9 years, an estimated 250,000 litres of diesel usage have been avoided](https://www.cbc.ca/news/canada/newfoundland-labrador/solar-nunatsiavut-1.6565534) each year. This does not account for the fuel needed to transport the diesel to the remote communities. The small-scale solar systems are expected to meet between 20 to 90 per cent of the demand during peak times in summer.  The Nunatsiavut government is also planning to install a 2.3 MW wind turbine behind the Nain water tower which will increase the region’s renewable energy capacity. This expansion of renewable energy is a step toward the government’s energy sovereignty plan. 