## Cutting Oilsands' Emissions
####  Erica Beattie

The [Financial Post](https://calgaryherald.com/business/energy/time-is-incredibly-tight-new-report-adds-clarity-to-challenge-of-cutting-oilsands-emissions) released an article earlier this week on a new report from S&P Global discussing the challenges of cutting oilsands' emissions. Production in Canada's oilsands sector has nearly doubled in the past decade or so, but now it will have to reverse this in order to meet the country's goal of 40 per cent climate change reduction by 2030. The report touches on how difficult this will be given the time constraint and the scale of investment needed to achieve emission reductions.

The federal government has also set [mandates in the transportation sector](https://www.canada.ca/en/transport-canada/news/2022/04/minister-of-transport-announces-the-expansion-of-the-incentives-for-zero-emission-vehicles-program.html) requiring that all new vehicles sold must be zero-emission by 2030. These are large asks for both industries that will heavily impact each one, and many are questioning the feasibility of these aggressive cuts. 

Carbon capture, which is the method of emissions reduction preferred by the oil sands industry, is discussed in the report. Alberta has already seen some investment in this technology, for example [Shell's Quest project](https://www.shell.ca/en_ca/about-us/projects-and-sites/quest-carbon-capture-and-storage-project.html) which was completed in 2016. But the province requires much more capture and sequestration capacity if industry is to meet its stated goals, let alone these new federal targets. And there's a short amount of time to get it done.