## OPEC vs. IEA - Who to believe?
#### <font size="+2"> [Erica Beattie](https://www.linkedin.com/in/erica-beattie-594b471a1/?originalSubdomain=ca)

The Organization of Petroleum Exporting Countries (OPEC) and the International Energy Agency (IEA) are two of the largest international energy organizations. Each year, they both create extensive  forecasts about the future of oil and energy; titled [World Oil Outlook (WOO)](https://woo.opec.org/chapter.php?chapterNr=311) for OPEC and [World Energy Outlook (WEO)](https://www.iea.org/reports/world-energy-outlook-2022/executive-summary) for IEA. Their documents for 2022 have recently been released. While one would assume the information presented in each would be relatively similar, given they both "speak for the same planet", [this article](https://energynow.ca/2022/11/david-yager-iea-versus-opec-opposing-views-on-the-future-of-energy-and-the-world/) points out some discrepancies in outlooks and approaches.

In such a turbulent and ever-changing world, faced with war and energy shortages, it may become difficult to know who to believe.