## Petro-Canada Sale?
#### Erica Beattie

Suncor Energy Corp. announced on Monday that they have reached an agreement with activist investor Elliot Investment Management LP, which will see three new independent directors added to the board. Two of these directors will have the task of searching for a new CEO, after Mark Little resigned earlier this month following the death of a worker on site. Another responsibility of the board will be to form a new committee to review Suncor's downstream retail business. This is where the potential sale of its retail gas station network came to be, and its estimated value is between $5-$8 billion.  

Elliot believes that these actions can lead to improvements in Suncor's safety measures, reliability, operations excellence, and industry leadership. Other analysts are more hesitant about these proposed changes and do not see the connection between the company's lagging performance and unlocked downstream or retail value. The idea that is shared between all parties is that some level of chnage at the corporate level of Suncor is required.

More details of this agreement can be found in the [original article.](https://financialpost.com/commodities/energy/suncor-energy-reaches-deal-with-activist-elliott-investment)

Now that there is talk about the sale of Petro-Canada gas stations, the question is who will be the buyer? 
[Another article in the Financial Post](https://financialpost.com/commodities/energy/oil-gas/circle-k-owner-seen-as-potential-bidder-for-suncor-retail-unit) highlights Quebec's Alimentation Couche-Tard Inc. as a potential buyer. Petro-Canada would be a huge deal for most buyers, with a significant price tag - estimated at around $10 billion. The problem for Couche-Tard here is that the purchase of Petro-Canada could come with significant antitrust issues. Some analysts predict that other potential buyers could be Parkland Corp., large retailers such as EG Group Ltd. and 7-Eleven Inc., or even international players. These companies have yet to comment on the matter, but it will be interesting to watch what happens to Suncor and the Petro-Canada stations in the near future.