## Plastics in a Circular Economy

#### <font size="+2">  Keshinee Moonian

Numerous Canadian companies are trying to solve the plastic waste challenge.

Calgary-based Inter Pipeline, which spent $3 billion to develop the Heartland Petrochemical Complex (HPC), has committed to advancing a circular plastics economy in Canada. “We believe that plastic is a valuable commodity that belongs in the economy, not the environment,” says Lorraine Royer, InterPipeline’s director of government and stakeholder relations. “We look for solutions so that our impact is as little as it can be.” 

A circular economy for plastics is an economic model where plastics never become waste, but rather are reused, recycled and recovered at the end of their life, according to Elena Mantagaris, vice-president of plastics with the Chemistry Industry Association of Canada (CIAC), of which Inter Pipeline is a member. 

Inter Pipeline has partnered with the Northern Alberta Institute of Technology (NAIT) to create Plastics Research in Action (PRIA), with a mandate to study micro-plastics in water and to develop ways to use hard-to-recycle plastics in other products.   

[New Alberta Plastics Plant Commits to Supporting a Circular Economy](https://energynow.ca/2022/05/new-alberta-plastics-plant-commits-to-supporting-a-circular-economy/)

