## Rare Earth Mining for Renewable Energy
#### [Marc Vermette](https://www.linkedin.com/in/marc-vermette/)

Michele Bustamante, a researcher at the USA Natural Resources Defense Council highlights the [importance of rare earth elements](https://www.iea.org/reports/the-role-of-critical-minerals-in-clean-energy-transitions/executive-summary) in the construction of renewable energy projects (wind turbine magnets, battery technology, etc.), but also points out the [worrying negative environmental effects](https://hir.harvard.edu/not-so-green-technology-the-complicated-legacy-of-rare-earth-mining/) of mining them (chemical spills, wastewater, pollution).

Thomas Lograsso, the director of the Critical Materials Institute highlights the importance of the mining industry's desire to invest in more sustainable resource extraction practices to help resolve these negative effects.

It is the “low hanging fruit” that will yield the most results, like basic hardware upgrades, says Julie Klinger, a geographer at the University of Delaware.

While the only rare earth mine in North America, located in California, was [mostly inactive until recently](https://www.voanews.com/a/usa_california-mine-becomes-key-part-push-revive-us-rare-earths-processing/6200183.html), other locations are already feeling the effects of mining and processing these resources necessary for the renewable energy boom.

In 2010, China’s State Council wrote that the rare earth industry was causing “severe damage to the ecological environment.”
The release of heavy metals and other pollutants during mining led to “destruction of vegetation and pollution.”

[Original Article](https://www.sciencenews.org/article/rare-earth-mining-renewable-energy-future)