## RBC pressed to cut fossil-fuel financing
#### [Erica Beattie](https://www.linkedin.com/in/erica-beattie-594b471a1/?originalSubdomain=ca)

Shareholders are putting pressure on banks including the Royal Bank of Canada,, JPMorgan Chase & Co., and Citigroup Inc to reduce financing of fossil fuels to meet global climate goals. Banks are being asked by investors to phase out their funding of oil and gas exploration and development, and to oyt forward plans to better align their lending services with climate goals. 

Additionally, three New York City pension plans have said that they want lenders, such as RBC, to disclose their 2030 targets to cut greenhouse gas emissions on an absolute basis instead of an intensity basis. 

Some progress has been made, but it is not quite enough. For example, banks organized a total of $533 billion of lending for the oil, gas, and coal sectors last year, compared to $656 in 2021. Ultimately, banks are being asked by shareholders to set policies and increase their transparency when it comes to how they are achieving their climate goals.

The investors' reasoning behind this is that without these policies in place, banks will not be able to meet their own climate targets and risk possible fines from regulators that want to prevent companies from "making exaggerated environmental claims" or *greenwashing*. The idea is to encourage banks to finance companies that are certified to be on a net-zero pathway.

See original article [here](https://financialpost.com/commodities/energy/oil-gas/royal-bank-of-canada-fossil-fuel-financing-carbon-emissions)