## (Overly?) Optimistic on AB renewables
#### Marc Vermette

A [report from research firm, Rystad Energy](https://oilprice.com/Energy/Energy-General/Canadas-Oil-Province-Will-Soon-Be-A-Renewable-Energy-Leader.html), suggests that Alberta may be poised to become the predominant contributor of renewable power in Canada. But, we've got some questions.

To put it bluntly, the conclusions attributed to the study are likely to be mind-boggling to anyone following Alberta's market closely. Rystad concludes that Alberta will see almost 10 GW of installed renewable capacity before next year, with that total expected to double by 2025 to almost 21 GW. To put that number into perspective, Canada's [total wind and utlity-scale solar capacity in 2021 was about 16 GW](https://renewablesassociation.ca/by-the-numbers/).

“Alberta [may] race ahead of Canada’s other provinces and take the top spot in the country’s green table, outpacing Ontario,” the Rystad report said, “The introduction of corporate power purchase agreements (PPAs) in Alberta — a contract for a private operator to sell energy straight to the local grid at a set price — has incentivized developers." Sure, but that's not enough to get you from here to there.

Alberta is, without a doubt, moving rapidly to a more renewable-intensive grid. But, there's something wrong with these numbers. In order to get 21GW of capacity installed by 2025, you'd need every project currently in [AESO's connection queue](https://www.aeso.ca/grid/projects/connection-project-reporting/) to be completed and connected by 2025, and more. And you'd need somewhere for that power to go a lot of the time since Alberta's peak loads are, currently, [less than 12GW](https://www.aeso.ca/assets/Uploads/market-and-system-reporting/2021-Annual-Market-Stats-Final.pdf). 

To put these numbers into further perspective, recent AESO forecasts, even in the most accelerated renewables development scenario in their (recent net-zero report)[https://www.aeso.ca/market/net-zero-emissions-pathways/] showed less than 6GW of installed wind and solar capacity by the end of 2025. 

We'll be watching for more detailed reaction to these numbers of the next week or so.

[Original Article](https://financialpost.com/executive/executive-summary/posthaste-how-the-fossil-fuel-heartland-will-become-canadas-green-energy-leader-in-three-years)