## Shell's Renewable Project in the Philippines

#### [Yousaff Habib](https://www.linkedin.com/in/yousaff-habib-6684891a5/)

A subdivision of Shell PLC, Shell Overseas Investments B.V. has just signed an agreement with Philippines Emerging Power Inc to build a 1 gigawatt (GW) solar power system, large enough to power roughly 1.2 million homes in the Philippines. Shell aims to become net zero by 2050, and this project is one of many that they have undertaken to reach this goal. The project can scale up to 3 GW, according to Shell. With 4.7 GW of renewable energy capacity currently on their books, this agreement will go a long way to advancing Shell's emissions reduction goals. The London-based oil and gas giant is committing to similar initiatives in other countries as well, including funding research into renewables and the generation of green hydrogen. This push for sustainability is a sentiment being echoed across a number of companies, but Shell stands out in their commitment, perhaps in part because [Dutch courts have pushed them harder than others](https://www.nytimes.com/2021/05/26/business/royal-dutch-shell-climate-change.html). 

For more information about the project, check out [this from Shell](https://www.shell.com.ph/motorists/inside-our-stations/next-generation-sustainability-now.html) as well as [this from Reuters](https://www.reuters.com/business/sustainable-business/shell-philippine-partner-build-1-gw-renewable-energy-capacity-2022-07-01/).