## South Asia's Energy Crisis
#### Debosree Mukherjee

For the past few months, energy shortages caused by high fuel prices have been seen around the world. Earlier this summer, India faced unprecedented power shortages due to high temperatures and low coal supplies. Reports suggest that [India may be heading towards another power crisis](https://economictimes.indiatimes.com/industry/energy/power/india-heading-towards-another-power-crisis-in-july-august-report/articleshow/91868775.cms) in August.

There are fears the crisis will worsen in some parts of South Asia due to plummeting foreign exchange reserves and increasing import costs. Growing numbers of [fuel suppliers are avoiding selling to Pakistan and Sri Lanka](https://www.bloomberg.com/news/articles/2022-07-27/crippling-energy-crisis-set-to-worsen-for-debt-ridden-south-asia#xj4y7vzkg) due to concerns about payment capabilities. About a quarter of Pakistan’s power-generation capacity has been shut because of fuel shortages. Despite 21.3% inflation, highest in over a decade, the country [raised its power prices due to rising generation costs](https://www.reuters.com/business/energy/pakistan-raises-power-prices-amid-energy-crisis-despite-rampant-inflation-2022-07-26/). Sri Lanka amid bankruptcy and crippling fuel shortage, introduced a [National Fuel Pass](https://www.business-standard.com/article/international/lanka-introduces-fuel-pass-amid-protesters-vow-to-change-system-122071700977_1.html) to ration fuel. 

Recently, Bangladesh joined Pakistan and Sri Lanka and became the third South Asian country to seek [monetary support](https://www.reuters.com/markets/asia/bangladesh-seeking-imf-loan-finance-minister-confirms-paper-2022-07-27/) from the International Monetary Fund due to rising energy and food prices. Like Pakistan, India, and Sri Lanka, Bangladesh is heavily dependent on imports for power generation, and often relies on spot prices. In 2021, the country bought 42% of its LNG from the spot market. Due to declining foreign reserves and skyrocketing prices, the country is struggling to import LNG and also diesel fuel. The government [suspended operations at diesel-run power plants](https://bdnews24.com/economy/bangladesh-to-shut-diesel-run-power-plants-keep-fuel-stations-closed-once-a-week-amid-energy-crisis) and announced that fuel stations will be closed for a day every week. From July 19, two hours of mandatory power cuts every day was made official to manage the situation. However, some semiurban and rural parts of the country are only getting [12 hours of electricity per day](https://asia.nikkei.com/Economy/Blackouts-bedevil-Bangladesh-as-South-Asia-forex-worries-mount).
