## Spending on Renewables Matches Fossil Fuels
#### [Marc Vermette](https://www.linkedin.com/in/marc-vermette/)

For the first time, the world spent $1.1 trillion USD annually on renewable energy. This is the same amount that was spent on producing oil and gas.

Solar and wind power accounted for 45% of this spending, and EVs for 43%.

The 2022 renewable spending was 31% greater than 2021, but still far from what is needed to reach net zero by 2050. 

A [study by BloombergNEF](https://about.bnef.com/blog/global-low-carbon-energy-technology-investment-surges-past-1-trillion-for-the-first-time/) shows that annual spending would have to triple from its present all-time high to be able to reach this goal, as investment in oil and gas continues to rise.

As for a win we CAN claim, when we factor in the strengthening of renewable energy supply chains, power grids, and financing projects, the global spending on the energy transition exceeds that of oil and gas production by nearly $500 billion.

[Original Article](https://www.bloomberg.com/news/articles/2023-01-26/global-clean-energy-investments-match-fossil-fuel-for-first-time)