## TMX Costs and Delays

#### [Erica Beattie](https://www.linkedin.com/in/erica-beattie-594b471a1/)

Pipelines have become a political wedge issue in Canada, and our pipeline politics will be much more tense in the wake of a [report from Canada's Parliamentary Budget Office](https://www.pbo-dpb.ca/en/publications/RP-2223-011-S--trans-mountain-pipeline-update--reseau-pipelines-trans-mountain-mise-jour) that concluded that the TransMountain Expansion Project (TMX) is "no longer a profitable undertaking." The [original cost for the project](https://www.cer-rec.gc.ca/en/applications-hearings/view-applications-projects/trans-mountain-expansion/project-background.html#:~:text=On%20February%2022%2C%202019%2C%20The,to%20the%20Government%20of%20Canada) was estimated at $5.4 billion, and the project was to be completed in 2019. The cost has now quadrupled, with the most recent estimates sitting at $21.4 billion. The project is also substantially delayed, with the completion date now set for late 2023.

[This article by the Canadian Energy Centre](https://www.canadianenergycentre.ca/yager-architects-of-tmx-cost-explosion-and-delays-remain-unaccountable/) discusses who should be held accountable for these tremendously costly delays. But, the main questions to be asked are likely who will be responsible for these costs. The Parliamentary Budget Office report does not detail the degree to which some increased costs may flow through to shippers. More importantly, the report does not actually conclude that the project will lose money: on the contrary, it concludes that the project will likely earn positive profits, just not enough to recoup a 7.8% opportunity cost of capital.  Whether or not that is the correct opportunity cost of capital to use for a major federally-owned project is debatable, especially with borrowing costs on the rise, but many articles written on the TMX costs overlooked this important detail.