## US Carbon Offsets
#### [Marc Vermette](https://www.linkedin.com/in/marc-vermette/)

USA Climate Envoy John Kerry revealed a [carbon offset plan](https://www.protocol.com/bulletins/john-kerry-carbon-credits-cop27) that would allow corporations to fund renewable energy projects in developing countries that are struggling to transition away from fossil fuels.

This plan, to be released in the coming year, will create carbon offsets to reward investments in projects that help accelerate renewable energy projects in developing countries. Businesses can then buy these offsets to balance out some portion of their CO2 emissions.

However, voluntary carbon offset programs are [often criticized](https://www.washingtonpost.com/business/energy/what-are-carbon-offsets-and-how-many-really-work/2022/11/09/44f330c4-6079-11ed-a131-e900e4a6336b_story.html) for being insufficiently regulated, and for allowing governments and corporations to compromise net-zero emission goals.

Climate policy expert [Rachel Cleetus](https://www.ucsusa.org/about/people/rachel-cleetus) weighed in, arguing that a “voluntary carbon credit program” is “not [the] answer in a world already on fire, underwater and facing mounting climate losses and damage.”

[Original Article](https://www.cnbc.com/2022/11/09/us-launches-carbon-offset-program-to-help-developing-countries.html)