## Record Tree Losses

#### Keshinee Moonian

The number of trees destroyed in northern parts of Russia, Canada and Alaska in 2021 was up 30% from 2020. Climate change is considered one of the main drivers of this phenomenon, with hotter and drier conditions causing more wildfires and more damage from insects.
 
Tree losses also continued at high levels in tropical areas, with the non-fire related destruction increasing by 9% overall. In some main states in the western Amazon area, losses were as high as 25%.
 
Some researchers fear that the Brazilian rainforest “may be approaching a tipping point when it emits more carbon than it stores.” This will hinder its role in limiting the rise in global temperatures this century.
 
On a more positive note, Indonesia curbed tree losses for the fifth year in a row. Indonesian initiatives which have proved successful so far include a permanent moratorium on converting primary forest and peatland for palm oil, and a commitment in their national climate plan to reduce emissions from forests. 
 
Countries committed to "halt and reverse forest loss by 2030” at COP26, which will require considerable and rapid action in many countries. Wildfires are linked to the hotter, drier conditions that climate change is bringing, and this will compound the local effects of deforestation.

[Climate change: Record tree losses in 2021 in northern regions](https://www.bbc.com/news/science-environment-61248596)

