## Renewable Investments Needed

#### [Marc Vermette](https://www.linkedin.com/in/marc-vermette/)

It's IEA World Energy Outlook Week, so plenty of charts from them are coming your way in the next while!

The IEA says that renewables spending needs to more than triple globally in order to be on track to meet the goals set out in the Paris climate accord. This means that annual investments into renewable energy will need to reach $1.3 trillion per year by 2030.

This amount is over triple the $390 billion spent annually on renewables currently. However, the $1.3 trillion goal is not unprecedented for the energy industry. This amount would be equal to a previous record, set in 2014, for investment into fossil fuels.

In order to keep global warming to less than 2 degrees Celsius, wealthy countries will need to eliminate emissions entirely from their power sectors by 2035. Developing economies would need to follow suit by 2040, said the IEA in its World Energy Outlook.

Currently, decarbonizing the electricity sector is one of the cheapest and easiest ways to cut emissions. Solar and wind technology [prices have risen recently](https://www.energyintel.com/00000184-0971-d1bb-a39f-3df73fee0000) due to higher commodity prices and issues within their supply chains. However, they are becoming increasingly competitive, especially compared to other, more expensive, fossil-fuel alternatives.

[Original Article](https://www.bloomberg.com/news/articles/2022-10-27/renewables-need-1-3-trillion-per-year-by-2030-for-climate-goals?leadSource=uverify%20wall)