## Largest Flow Battery in the World
#### [Yousaff Habib](https://www.linkedin.com/in/yousaff-habib-6684891a5/)

For this weeks chart, I have some interesting news that ties into one of my previous stories. You may recall my chart on vanadium flow batteries and their potential usefulness in renewable energy storage. Last month, the Chinese city of Dalian switched on the Dalian Flow Battery Energy Storage Peak-shaving Power Station, a power bank for the city, boasting an initial capacity of 400MWh and an output of 100MW. There are plans to scale the battery up to a 200MW output and 800MWh capacity. The battery aims to reduce peaks and valleys by storing energy, increasing grid reliability in the region. As I've mentioned in past charts, China is taking big steps to be energy independent, and the continual innovation and adoption of new technologies has allowed them to iterate on their work. While the idea is nothing new, the use of a vanadium flow battery this large is a promising sign that the technology will see more widespread adoption. Considering that lithium supplies are beginning to [see strain](https://www.weforum.org/agenda/2022/07/electric-vehicles-world-enough-lithium-resources/), it may be the very thing we need to progress with renewable. To read more about the Dalian Flow Battery, check out [this](https://newatlas.com/energy/worlds-largest-flow-battery-grid-china/) article.