##  Solar in Edmonton
#### [Debosree Mukherjee](https://www.linkedin.com/in/debosree-mukherjee/)

On Tuesday, September 20th, EPCOR officially opened the kīsikāw pīsim solar farm located in southwest Edmonton. The farm is on traditional Enoch Cree Nation territory and the name was decided at a traditional Indigenous naming ceremony in January.  [This new farm has 30,350 solar panels](https://globalnews.ca/news/9143118/epcor-energizes-edmonton-river-valley-solar-farm/) and will provide the E.L. Smith Water Treatment plant with up to half of the power it needs. The water treatment plant provides 65% of the water used by Edmonton and 65 regions around the city. The kīsikāw pīsim solar farm will generate enough power to cut an estimated 14,000 tonnes of greenhouse gas emissions every year.  Power from the solar panels can also be stored to be used when there is not enough sunlight to produce electricity. When more electricity than what the water treatment plant needs is generated, the electricity will go to the grid. According to EPCOR, it is Canada’s largest municipal solar farm with a battery energy storage system and smart grid.

Due to concerns regarding the ecological impact of developing a solar farm in the river valley area, the project went through a long environmental evaluation and regulatory process to be approved. The farm received $10 million in federal grants, and Edmontonians have been paying an extra 10 to 15 cents per month on their bill since 2017 to fund the project.